language: node_js

node_js: 7.7.2

chai: 3.5.0

sudo: required

before_script:
    - sudo $(which npm) install -g grunt
    - sudo $(which npm) install -g grunt-cli

script:
    - grunt --verbose --force

after_succes:
    - grunt coveralls
